language: java

addons:
  sonarcloud:
    organization: "snottierwhale"
    token:
   secure: "iO/jGLWOQDjh62uFh9vvraaGiLvF4hMpmkbQWiAVJamOeMDcfsTH6uXFEzxFJNW0x9XmRnRy5jsrUZNnEF7MKSj5+KE/yk1QUzYlhOoEovYT5AEt+qG08/8ZeJcRjVVZUmKfAwhF4j1OU9WtpFG5r5KUopyhLF6qJys2fjg+8JdTnhs55gHfl/JFrupNFXDiQ5IvSfFxkJYZuko/ewmpB5im3zIap9YT6eTlNEHTZJ/xN5MXAFTJy6tUDTibp+gm50Tr/Fms7QO0XZM8QtzpClhq1NskVBfC5fDfkiwIgWQC6Q6SF9N3UnpRkjvsmMSxzzh+jDo66H8m9vYR4fCdJAq2c578x6jZPLX6dWb0H5tqd3tCrctQlc/2AxVAuVhCFJQfNHoeRLX74lHMcfh+2cCOaNjjs2ULwn2x6qZ4btrkIqtgM+U6ydz2kIDs3SrIZQWuDYuPTwxZT9SRW6PAVXYX+nfRSkhzS6yrZJ+7KatMaMT2P6Mwq8eLozm1sQ+/1EVXVSjMpCZMD7XWThq+LoQdFyziLccy4QUspz58XSv6dGydphdF/xXlWnvUiPmng9k92FOzWSyoVME1VFSMBX6Ei7aBu23L8iX9sqIigEOXd5CX5L7sQZee54sZShjt6EPcKPqDNczB+br8mLsjRfroritu5q5Vml/TRiVoHW8="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  
